version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: identity_postgres
    restart: always
    environment:
      POSTGRES_USER: identity
      POSTGRES_PASSWORD: random@123
      POSTGRES_DB: identity
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
